// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: adgroup/v1/adgroup.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdgroupId   int64  `protobuf:"varint,1,opt,name=adgroup_id,json=adgroupId,proto3" json:"adgroup_id,omitempty"`
	AdgroupName string `protobuf:"bytes,2,opt,name=adgroup_name,json=adgroupName,proto3" json:"adgroup_name,omitempty"`
}

func (x *CreateAdgroupRequest) Reset() {
	*x = CreateAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdgroupRequest) ProtoMessage() {}

func (x *CreateAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdgroupRequest.ProtoReflect.Descriptor instead.
func (*CreateAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAdgroupRequest) GetAdgroupId() int64 {
	if x != nil {
		return x.AdgroupId
	}
	return 0
}

func (x *CreateAdgroupRequest) GetAdgroupName() string {
	if x != nil {
		return x.AdgroupName
	}
	return ""
}

type CreateAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdgroupId int64 `protobuf:"varint,1,opt,name=adgroup_id,json=adgroupId,proto3" json:"adgroup_id,omitempty"`
}

func (x *CreateAdgroupReply) Reset() {
	*x = CreateAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdgroupReply) ProtoMessage() {}

func (x *CreateAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdgroupReply.ProtoReflect.Descriptor instead.
func (*CreateAdgroupReply) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdgroupReply) GetAdgroupId() int64 {
	if x != nil {
		return x.AdgroupId
	}
	return 0
}

type UpdateAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAdgroupRequest) Reset() {
	*x = UpdateAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdgroupRequest) ProtoMessage() {}

func (x *UpdateAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdgroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{2}
}

type UpdateAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAdgroupReply) Reset() {
	*x = UpdateAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdgroupReply) ProtoMessage() {}

func (x *UpdateAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdgroupReply.ProtoReflect.Descriptor instead.
func (*UpdateAdgroupReply) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{3}
}

type DeleteAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAdgroupRequest) Reset() {
	*x = DeleteAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdgroupRequest) ProtoMessage() {}

func (x *DeleteAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdgroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{4}
}

type DeleteAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAdgroupReply) Reset() {
	*x = DeleteAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdgroupReply) ProtoMessage() {}

func (x *DeleteAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdgroupReply.ProtoReflect.Descriptor instead.
func (*DeleteAdgroupReply) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{5}
}

type GetAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAdgroupRequest) Reset() {
	*x = GetAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdgroupRequest) ProtoMessage() {}

func (x *GetAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdgroupRequest.ProtoReflect.Descriptor instead.
func (*GetAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{6}
}

type GetAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAdgroupReply) Reset() {
	*x = GetAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdgroupReply) ProtoMessage() {}

func (x *GetAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdgroupReply.ProtoReflect.Descriptor instead.
func (*GetAdgroupReply) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{7}
}

type ListAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAdgroupRequest) Reset() {
	*x = ListAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdgroupRequest) ProtoMessage() {}

func (x *ListAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdgroupRequest.ProtoReflect.Descriptor instead.
func (*ListAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{8}
}

type ListAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAdgroupReply) Reset() {
	*x = ListAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adgroup_v1_adgroup_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdgroupReply) ProtoMessage() {}

func (x *ListAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_adgroup_v1_adgroup_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdgroupReply.ProtoReflect.Descriptor instead.
func (*ListAdgroupReply) Descriptor() ([]byte, []int) {
	return file_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{9}
}

var File_adgroup_v1_adgroup_proto protoreflect.FileDescriptor

var file_adgroup_v1_adgroup_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e,
	0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x33, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xd6, 0x03, 0x0a, 0x07, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x6e, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0d, 0x22, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x59, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x59, 0x0a, 0x0d,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x24, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x50, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0b, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x32,
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x1e, 0x61, 0x64, 0x2d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adgroup_v1_adgroup_proto_rawDescOnce sync.Once
	file_adgroup_v1_adgroup_proto_rawDescData = file_adgroup_v1_adgroup_proto_rawDesc
)

func file_adgroup_v1_adgroup_proto_rawDescGZIP() []byte {
	file_adgroup_v1_adgroup_proto_rawDescOnce.Do(func() {
		file_adgroup_v1_adgroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_adgroup_v1_adgroup_proto_rawDescData)
	})
	return file_adgroup_v1_adgroup_proto_rawDescData
}

var file_adgroup_v1_adgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_adgroup_v1_adgroup_proto_goTypes = []any{
	(*CreateAdgroupRequest)(nil), // 0: api.adgroup.v1.CreateAdgroupRequest
	(*CreateAdgroupReply)(nil),   // 1: api.adgroup.v1.CreateAdgroupReply
	(*UpdateAdgroupRequest)(nil), // 2: api.adgroup.v1.UpdateAdgroupRequest
	(*UpdateAdgroupReply)(nil),   // 3: api.adgroup.v1.UpdateAdgroupReply
	(*DeleteAdgroupRequest)(nil), // 4: api.adgroup.v1.DeleteAdgroupRequest
	(*DeleteAdgroupReply)(nil),   // 5: api.adgroup.v1.DeleteAdgroupReply
	(*GetAdgroupRequest)(nil),    // 6: api.adgroup.v1.GetAdgroupRequest
	(*GetAdgroupReply)(nil),      // 7: api.adgroup.v1.GetAdgroupReply
	(*ListAdgroupRequest)(nil),   // 8: api.adgroup.v1.ListAdgroupRequest
	(*ListAdgroupReply)(nil),     // 9: api.adgroup.v1.ListAdgroupReply
}
var file_adgroup_v1_adgroup_proto_depIdxs = []int32{
	0, // 0: api.adgroup.v1.Adgroup.CreateAdgroup:input_type -> api.adgroup.v1.CreateAdgroupRequest
	2, // 1: api.adgroup.v1.Adgroup.UpdateAdgroup:input_type -> api.adgroup.v1.UpdateAdgroupRequest
	4, // 2: api.adgroup.v1.Adgroup.DeleteAdgroup:input_type -> api.adgroup.v1.DeleteAdgroupRequest
	6, // 3: api.adgroup.v1.Adgroup.GetAdgroup:input_type -> api.adgroup.v1.GetAdgroupRequest
	8, // 4: api.adgroup.v1.Adgroup.ListAdgroup:input_type -> api.adgroup.v1.ListAdgroupRequest
	1, // 5: api.adgroup.v1.Adgroup.CreateAdgroup:output_type -> api.adgroup.v1.CreateAdgroupReply
	3, // 6: api.adgroup.v1.Adgroup.UpdateAdgroup:output_type -> api.adgroup.v1.UpdateAdgroupReply
	5, // 7: api.adgroup.v1.Adgroup.DeleteAdgroup:output_type -> api.adgroup.v1.DeleteAdgroupReply
	7, // 8: api.adgroup.v1.Adgroup.GetAdgroup:output_type -> api.adgroup.v1.GetAdgroupReply
	9, // 9: api.adgroup.v1.Adgroup.ListAdgroup:output_type -> api.adgroup.v1.ListAdgroupReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adgroup_v1_adgroup_proto_init() }
func file_adgroup_v1_adgroup_proto_init() {
	if File_adgroup_v1_adgroup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adgroup_v1_adgroup_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adgroup_v1_adgroup_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adgroup_v1_adgroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adgroup_v1_adgroup_proto_goTypes,
		DependencyIndexes: file_adgroup_v1_adgroup_proto_depIdxs,
		MessageInfos:      file_adgroup_v1_adgroup_proto_msgTypes,
	}.Build()
	File_adgroup_v1_adgroup_proto = out.File
	file_adgroup_v1_adgroup_proto_rawDesc = nil
	file_adgroup_v1_adgroup_proto_goTypes = nil
	file_adgroup_v1_adgroup_proto_depIdxs = nil
}
