// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v5.26.1
// source: adgroup/v1/adgroup.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAdgroupCreateAdgroup = "/api.adgroup.v1.Adgroup/CreateAdgroup"

type AdgroupHTTPServer interface {
	CreateAdgroup(context.Context, *CreateAdgroupRequest) (*CreateAdgroupReply, error)
}

func RegisterAdgroupHTTPServer(s *http.Server, srv AdgroupHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/adgroup", _Adgroup_CreateAdgroup0_HTTP_Handler(srv))
}

func _Adgroup_CreateAdgroup0_HTTP_Handler(srv AdgroupHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAdgroupRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAdgroupCreateAdgroup)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAdgroup(ctx, req.(*CreateAdgroupRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAdgroupReply)
		return ctx.Result(200, reply)
	}
}

type AdgroupHTTPClient interface {
	CreateAdgroup(ctx context.Context, req *CreateAdgroupRequest, opts ...http.CallOption) (rsp *CreateAdgroupReply, err error)
}

type AdgroupHTTPClientImpl struct {
	cc *http.Client
}

func NewAdgroupHTTPClient(client *http.Client) AdgroupHTTPClient {
	return &AdgroupHTTPClientImpl{client}
}

func (c *AdgroupHTTPClientImpl) CreateAdgroup(ctx context.Context, in *CreateAdgroupRequest, opts ...http.CallOption) (*CreateAdgroupReply, error) {
	var out CreateAdgroupReply
	pattern := "/v1/adgroup"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAdgroupCreateAdgroup))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
