// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: gdt/adgroup/v1/adgroup.proto

package v1

import (
	response "ad-marketing/api/common/response"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdgroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdgroupId        int64  `protobuf:"varint,1,opt,name=adgroup_id,json=adgroupId,proto3" json:"adgroup_id,omitempty"`
	AdgroupName      string `protobuf:"bytes,2,opt,name=adgroup_name,json=adgroupName,proto3" json:"adgroup_name,omitempty"`
	AdvertiserId     int64  `protobuf:"varint,3,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	CompanyId        int64  `protobuf:"varint,4,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	ConfiguredStatus string `protobuf:"bytes,5,opt,name=configured_status,json=configuredStatus,proto3" json:"configured_status,omitempty"`
	BeginDate        string `protobuf:"bytes,6,opt,name=begin_date,json=beginDate,proto3" json:"begin_date,omitempty"`
	EndDate          string `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	TimeSeries       string `protobuf:"bytes,8,opt,name=time_series,json=timeSeries,proto3" json:"time_series,omitempty"`
	CreatedAt        int64  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        int64  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *AdgroupInfo) Reset() {
	*x = AdgroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdgroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdgroupInfo) ProtoMessage() {}

func (x *AdgroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdgroupInfo.ProtoReflect.Descriptor instead.
func (*AdgroupInfo) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{0}
}

func (x *AdgroupInfo) GetAdgroupId() int64 {
	if x != nil {
		return x.AdgroupId
	}
	return 0
}

func (x *AdgroupInfo) GetAdgroupName() string {
	if x != nil {
		return x.AdgroupName
	}
	return ""
}

func (x *AdgroupInfo) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *AdgroupInfo) GetCompanyId() int64 {
	if x != nil {
		return x.CompanyId
	}
	return 0
}

func (x *AdgroupInfo) GetConfiguredStatus() string {
	if x != nil {
		return x.ConfiguredStatus
	}
	return ""
}

func (x *AdgroupInfo) GetBeginDate() string {
	if x != nil {
		return x.BeginDate
	}
	return ""
}

func (x *AdgroupInfo) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *AdgroupInfo) GetTimeSeries() string {
	if x != nil {
		return x.TimeSeries
	}
	return ""
}

func (x *AdgroupInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AdgroupInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adgroup *AdgroupInfo `protobuf:"bytes,1,opt,name=adgroup,proto3" json:"adgroup,omitempty"`
}

func (x *CreateAdgroupRequest) Reset() {
	*x = CreateAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdgroupRequest) ProtoMessage() {}

func (x *CreateAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdgroupRequest.ProtoReflect.Descriptor instead.
func (*CreateAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdgroupRequest) GetAdgroup() *AdgroupInfo {
	if x != nil {
		return x.Adgroup
	}
	return nil
}

type CreateAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResMsg *response.ResMsg         `protobuf:"bytes,1,opt,name=res_msg,json=resMsg,proto3" json:"res_msg,omitempty"`
	Data   *CreateAdgroupReply_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateAdgroupReply) Reset() {
	*x = CreateAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdgroupReply) ProtoMessage() {}

func (x *CreateAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdgroupReply.ProtoReflect.Descriptor instead.
func (*CreateAdgroupReply) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAdgroupReply) GetResMsg() *response.ResMsg {
	if x != nil {
		return x.ResMsg
	}
	return nil
}

func (x *CreateAdgroupReply) GetData() *CreateAdgroupReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAdgroupRequest) Reset() {
	*x = UpdateAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdgroupRequest) ProtoMessage() {}

func (x *UpdateAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdgroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{3}
}

type UpdateAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAdgroupReply) Reset() {
	*x = UpdateAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdgroupReply) ProtoMessage() {}

func (x *UpdateAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdgroupReply.ProtoReflect.Descriptor instead.
func (*UpdateAdgroupReply) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{4}
}

type DeleteAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdvertiserId int64   `protobuf:"varint,1,opt,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
	AdgroupId    []int64 `protobuf:"varint,2,rep,packed,name=adgroup_id,json=adgroupId,proto3" json:"adgroup_id,omitempty"`
}

func (x *DeleteAdgroupRequest) Reset() {
	*x = DeleteAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdgroupRequest) ProtoMessage() {}

func (x *DeleteAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdgroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAdgroupRequest) GetAdvertiserId() int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return 0
}

func (x *DeleteAdgroupRequest) GetAdgroupId() []int64 {
	if x != nil {
		return x.AdgroupId
	}
	return nil
}

type DeleteAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorAdgroupIds []*DeleteAdgroupReplyErrorAdgroupId `protobuf:"bytes,1,rep,name=error_adgroup_ids,json=errorAdgroupIds,proto3" json:"error_adgroup_ids,omitempty"`
}

func (x *DeleteAdgroupReply) Reset() {
	*x = DeleteAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdgroupReply) ProtoMessage() {}

func (x *DeleteAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdgroupReply.ProtoReflect.Descriptor instead.
func (*DeleteAdgroupReply) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAdgroupReply) GetErrorAdgroupIds() []*DeleteAdgroupReplyErrorAdgroupId {
	if x != nil {
		return x.ErrorAdgroupIds
	}
	return nil
}

type GetAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdgroupId []int64 `protobuf:"varint,1,rep,packed,name=adgroup_id,json=adgroupId,proto3" json:"adgroup_id,omitempty"`
}

func (x *GetAdgroupRequest) Reset() {
	*x = GetAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdgroupRequest) ProtoMessage() {}

func (x *GetAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdgroupRequest.ProtoReflect.Descriptor instead.
func (*GetAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{7}
}

func (x *GetAdgroupRequest) GetAdgroupId() []int64 {
	if x != nil {
		return x.AdgroupId
	}
	return nil
}

type GetAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adgroups []*AdgroupInfo `protobuf:"bytes,1,rep,name=adgroups,proto3" json:"adgroups,omitempty"`
}

func (x *GetAdgroupReply) Reset() {
	*x = GetAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdgroupReply) ProtoMessage() {}

func (x *GetAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdgroupReply.ProtoReflect.Descriptor instead.
func (*GetAdgroupReply) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{8}
}

func (x *GetAdgroupReply) GetAdgroups() []*AdgroupInfo {
	if x != nil {
		return x.Adgroups
	}
	return nil
}

type ListAdgroupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page         int32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize     int32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	AdgroupId    []int64 `protobuf:"varint,3,rep,packed,name=adgroup_id,json=adgroupId,proto3" json:"adgroup_id,omitempty"`
	AdgroupName  string  `protobuf:"bytes,4,opt,name=adgroup_name,json=adgroupName,proto3" json:"adgroup_name,omitempty"`
	AdvertiserId []int64 `protobuf:"varint,5,rep,packed,name=advertiser_id,json=advertiserId,proto3" json:"advertiser_id,omitempty"`
}

func (x *ListAdgroupRequest) Reset() {
	*x = ListAdgroupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdgroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdgroupRequest) ProtoMessage() {}

func (x *ListAdgroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdgroupRequest.ProtoReflect.Descriptor instead.
func (*ListAdgroupRequest) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{9}
}

func (x *ListAdgroupRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAdgroupRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAdgroupRequest) GetAdgroupId() []int64 {
	if x != nil {
		return x.AdgroupId
	}
	return nil
}

func (x *ListAdgroupRequest) GetAdgroupName() string {
	if x != nil {
		return x.AdgroupName
	}
	return ""
}

func (x *ListAdgroupRequest) GetAdvertiserId() []int64 {
	if x != nil {
		return x.AdvertiserId
	}
	return nil
}

type ListAdgroupReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResMsg *response.ResMsg       `protobuf:"bytes,1,opt,name=res_msg,json=resMsg,proto3" json:"res_msg,omitempty"`
	Data   *ListAdgroupReply_Data `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ListAdgroupReply) Reset() {
	*x = ListAdgroupReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdgroupReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdgroupReply) ProtoMessage() {}

func (x *ListAdgroupReply) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdgroupReply.ProtoReflect.Descriptor instead.
func (*ListAdgroupReply) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{10}
}

func (x *ListAdgroupReply) GetResMsg() *response.ResMsg {
	if x != nil {
		return x.ResMsg
	}
	return nil
}

func (x *ListAdgroupReply) GetData() *ListAdgroupReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateAdgroupReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdgroupId int64 `protobuf:"varint,1,opt,name=adgroup_id,json=adgroupId,proto3" json:"adgroup_id,omitempty"`
}

func (x *CreateAdgroupReply_Data) Reset() {
	*x = CreateAdgroupReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdgroupReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdgroupReply_Data) ProtoMessage() {}

func (x *CreateAdgroupReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdgroupReply_Data.ProtoReflect.Descriptor instead.
func (*CreateAdgroupReply_Data) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreateAdgroupReply_Data) GetAdgroupId() int64 {
	if x != nil {
		return x.AdgroupId
	}
	return 0
}

type DeleteAdgroupReplyErrorAdgroupId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdgroupId int64 `protobuf:"varint,1,opt,name=adgroup_id,json=adgroupId,proto3" json:"adgroup_id,omitempty"`
}

func (x *DeleteAdgroupReplyErrorAdgroupId) Reset() {
	*x = DeleteAdgroupReplyErrorAdgroupId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdgroupReplyErrorAdgroupId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdgroupReplyErrorAdgroupId) ProtoMessage() {}

func (x *DeleteAdgroupReplyErrorAdgroupId) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdgroupReplyErrorAdgroupId.ProtoReflect.Descriptor instead.
func (*DeleteAdgroupReplyErrorAdgroupId) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DeleteAdgroupReplyErrorAdgroupId) GetAdgroupId() int64 {
	if x != nil {
		return x.AdgroupId
	}
	return 0
}

type ListAdgroupReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageInfo *response.PageInfo `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	List     []*AdgroupInfo     `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListAdgroupReply_Data) Reset() {
	*x = ListAdgroupReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdgroupReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdgroupReply_Data) ProtoMessage() {}

func (x *ListAdgroupReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_gdt_adgroup_v1_adgroup_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdgroupReply_Data.ProtoReflect.Descriptor instead.
func (*ListAdgroupReply_Data) Descriptor() ([]byte, []int) {
	return file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP(), []int{10, 0}
}

func (x *ListAdgroupReply_Data) GetPageInfo() *response.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ListAdgroupReply_Data) GetList() []*AdgroupInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_gdt_adgroup_v1_adgroup_proto protoreflect.FileDescriptor

var file_gdt_adgroup_v1_adgroup_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x67, 0x64, 0x74, 0x2f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x76, 0x31,
	0x2f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e,
	0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61,
	0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xd9, 0x02, 0x0a, 0x0b, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x75, 0x72, 0x65, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x51, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x07, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e,
	0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x22,
	0xa7, 0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x5f, 0x6d, 0x73,
	0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x65, 0x73, 0x4d, 0x73,
	0x67, 0x12, 0x3f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x1a, 0x25, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x14, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x5a, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x11, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e,
	0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x52, 0x0f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x73, 0x1a,
	0x31, 0x0a, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x5f, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x22, 0x32, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x61, 0x64, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x64, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x08, 0x61, 0x64, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x61, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0xac, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x09, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x21, 0x0a,
	0x0c, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x23, 0x0a, 0x0d, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xea, 0x01, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x72, 0x65,
	0x73, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x4d, 0x73, 0x67, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x6c, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x32, 0xbc, 0x04, 0x0a, 0x07, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x7d,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x3a, 0x01, 0x2a, 0x22, 0x0f, 0x2f, 0x67,
	0x64, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x61, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x28,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67,
	0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x61, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x71, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67,
	0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x67, 0x64, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x79, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e,
	0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x12, 0x14, 0x2f, 0x67, 0x64,
	0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x6c, 0x69, 0x73,
	0x74, 0x42, 0x3a, 0x0a, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x67, 0x64, 0x74, 0x2e, 0x61, 0x64, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x22, 0x61, 0x64, 0x2d, 0x6d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x64, 0x74, 0x2f,
	0x61, 0x64, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gdt_adgroup_v1_adgroup_proto_rawDescOnce sync.Once
	file_gdt_adgroup_v1_adgroup_proto_rawDescData = file_gdt_adgroup_v1_adgroup_proto_rawDesc
)

func file_gdt_adgroup_v1_adgroup_proto_rawDescGZIP() []byte {
	file_gdt_adgroup_v1_adgroup_proto_rawDescOnce.Do(func() {
		file_gdt_adgroup_v1_adgroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_gdt_adgroup_v1_adgroup_proto_rawDescData)
	})
	return file_gdt_adgroup_v1_adgroup_proto_rawDescData
}

var file_gdt_adgroup_v1_adgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_gdt_adgroup_v1_adgroup_proto_goTypes = []any{
	(*AdgroupInfo)(nil),                      // 0: api.gdt.adgroup.v1.AdgroupInfo
	(*CreateAdgroupRequest)(nil),             // 1: api.gdt.adgroup.v1.CreateAdgroupRequest
	(*CreateAdgroupReply)(nil),               // 2: api.gdt.adgroup.v1.CreateAdgroupReply
	(*UpdateAdgroupRequest)(nil),             // 3: api.gdt.adgroup.v1.UpdateAdgroupRequest
	(*UpdateAdgroupReply)(nil),               // 4: api.gdt.adgroup.v1.UpdateAdgroupReply
	(*DeleteAdgroupRequest)(nil),             // 5: api.gdt.adgroup.v1.DeleteAdgroupRequest
	(*DeleteAdgroupReply)(nil),               // 6: api.gdt.adgroup.v1.DeleteAdgroupReply
	(*GetAdgroupRequest)(nil),                // 7: api.gdt.adgroup.v1.GetAdgroupRequest
	(*GetAdgroupReply)(nil),                  // 8: api.gdt.adgroup.v1.GetAdgroupReply
	(*ListAdgroupRequest)(nil),               // 9: api.gdt.adgroup.v1.ListAdgroupRequest
	(*ListAdgroupReply)(nil),                 // 10: api.gdt.adgroup.v1.ListAdgroupReply
	(*CreateAdgroupReply_Data)(nil),          // 11: api.gdt.adgroup.v1.CreateAdgroupReply.Data
	(*DeleteAdgroupReplyErrorAdgroupId)(nil), // 12: api.gdt.adgroup.v1.DeleteAdgroupReply.error_adgroup_id
	(*ListAdgroupReply_Data)(nil),            // 13: api.gdt.adgroup.v1.ListAdgroupReply.Data
	(*response.ResMsg)(nil),                  // 14: response.ResMsg
	(*response.PageInfo)(nil),                // 15: response.PageInfo
}
var file_gdt_adgroup_v1_adgroup_proto_depIdxs = []int32{
	0,  // 0: api.gdt.adgroup.v1.CreateAdgroupRequest.adgroup:type_name -> api.gdt.adgroup.v1.AdgroupInfo
	14, // 1: api.gdt.adgroup.v1.CreateAdgroupReply.res_msg:type_name -> response.ResMsg
	11, // 2: api.gdt.adgroup.v1.CreateAdgroupReply.data:type_name -> api.gdt.adgroup.v1.CreateAdgroupReply.Data
	12, // 3: api.gdt.adgroup.v1.DeleteAdgroupReply.error_adgroup_ids:type_name -> api.gdt.adgroup.v1.DeleteAdgroupReply.error_adgroup_id
	0,  // 4: api.gdt.adgroup.v1.GetAdgroupReply.adgroups:type_name -> api.gdt.adgroup.v1.AdgroupInfo
	14, // 5: api.gdt.adgroup.v1.ListAdgroupReply.res_msg:type_name -> response.ResMsg
	13, // 6: api.gdt.adgroup.v1.ListAdgroupReply.data:type_name -> api.gdt.adgroup.v1.ListAdgroupReply.Data
	15, // 7: api.gdt.adgroup.v1.ListAdgroupReply.Data.page_info:type_name -> response.PageInfo
	0,  // 8: api.gdt.adgroup.v1.ListAdgroupReply.Data.list:type_name -> api.gdt.adgroup.v1.AdgroupInfo
	1,  // 9: api.gdt.adgroup.v1.Adgroup.CreateAdgroup:input_type -> api.gdt.adgroup.v1.CreateAdgroupRequest
	3,  // 10: api.gdt.adgroup.v1.Adgroup.UpdateAdgroup:input_type -> api.gdt.adgroup.v1.UpdateAdgroupRequest
	5,  // 11: api.gdt.adgroup.v1.Adgroup.DeleteAdgroup:input_type -> api.gdt.adgroup.v1.DeleteAdgroupRequest
	7,  // 12: api.gdt.adgroup.v1.Adgroup.GetAdgroup:input_type -> api.gdt.adgroup.v1.GetAdgroupRequest
	9,  // 13: api.gdt.adgroup.v1.Adgroup.ListAdgroup:input_type -> api.gdt.adgroup.v1.ListAdgroupRequest
	2,  // 14: api.gdt.adgroup.v1.Adgroup.CreateAdgroup:output_type -> api.gdt.adgroup.v1.CreateAdgroupReply
	4,  // 15: api.gdt.adgroup.v1.Adgroup.UpdateAdgroup:output_type -> api.gdt.adgroup.v1.UpdateAdgroupReply
	6,  // 16: api.gdt.adgroup.v1.Adgroup.DeleteAdgroup:output_type -> api.gdt.adgroup.v1.DeleteAdgroupReply
	8,  // 17: api.gdt.adgroup.v1.Adgroup.GetAdgroup:output_type -> api.gdt.adgroup.v1.GetAdgroupReply
	10, // 18: api.gdt.adgroup.v1.Adgroup.ListAdgroup:output_type -> api.gdt.adgroup.v1.ListAdgroupReply
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_gdt_adgroup_v1_adgroup_proto_init() }
func file_gdt_adgroup_v1_adgroup_proto_init() {
	if File_gdt_adgroup_v1_adgroup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AdgroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdgroupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdgroupReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAdgroupReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAdgroupReplyErrorAdgroupId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gdt_adgroup_v1_adgroup_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdgroupReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gdt_adgroup_v1_adgroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gdt_adgroup_v1_adgroup_proto_goTypes,
		DependencyIndexes: file_gdt_adgroup_v1_adgroup_proto_depIdxs,
		MessageInfos:      file_gdt_adgroup_v1_adgroup_proto_msgTypes,
	}.Build()
	File_gdt_adgroup_v1_adgroup_proto = out.File
	file_gdt_adgroup_v1_adgroup_proto_rawDesc = nil
	file_gdt_adgroup_v1_adgroup_proto_goTypes = nil
	file_gdt_adgroup_v1_adgroup_proto_depIdxs = nil
}
