// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ad-marketing/app/gdt/adgroup/internal/biz"
	"ad-marketing/app/gdt/adgroup/internal/conf"
	"ad-marketing/app/gdt/adgroup/internal/data"
	"ad-marketing/app/gdt/adgroup/internal/server"
	"ad-marketing/app/gdt/adgroup/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDb(confData, logger)
	cmdable := data.NewRedisCmd(confData, logger)
	dataData, cleanup, err := data.NewData(logger, db, cmdable)
	if err != nil {
		return nil, nil, err
	}
	adgroupRepo := data.NewAdgroupRepo(dataData, logger)
	adgroupUseCase := biz.NewAdgroupUseCase(adgroupRepo, logger)
	adgroupService := service.NewAdgroupService(adgroupUseCase)
	grpcServer := server.NewGRPCServer(confServer, adgroupService, logger)
	httpServer := server.NewHTTPServer(confServer, adgroupService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
