// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: common/advertiser/v1/advertiser.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAdvertiserRequest) Reset() {
	*x = CreateAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertiserRequest) ProtoMessage() {}

func (x *CreateAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*CreateAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{0}
}

type CreateAdvertiserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAdvertiserReply) Reset() {
	*x = CreateAdvertiserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdvertiserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertiserReply) ProtoMessage() {}

func (x *CreateAdvertiserReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertiserReply.ProtoReflect.Descriptor instead.
func (*CreateAdvertiserReply) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{1}
}

type UpdateAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAdvertiserRequest) Reset() {
	*x = UpdateAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdvertiserRequest) ProtoMessage() {}

func (x *UpdateAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{2}
}

type UpdateAdvertiserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAdvertiserReply) Reset() {
	*x = UpdateAdvertiserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdvertiserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdvertiserReply) ProtoMessage() {}

func (x *UpdateAdvertiserReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdvertiserReply.ProtoReflect.Descriptor instead.
func (*UpdateAdvertiserReply) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{3}
}

type DeleteAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAdvertiserRequest) Reset() {
	*x = DeleteAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdvertiserRequest) ProtoMessage() {}

func (x *DeleteAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{4}
}

type DeleteAdvertiserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAdvertiserReply) Reset() {
	*x = DeleteAdvertiserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdvertiserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdvertiserReply) ProtoMessage() {}

func (x *DeleteAdvertiserReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdvertiserReply.ProtoReflect.Descriptor instead.
func (*DeleteAdvertiserReply) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{5}
}

type GetAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAdvertiserRequest) Reset() {
	*x = GetAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertiserRequest) ProtoMessage() {}

func (x *GetAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*GetAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{6}
}

type GetAdvertiserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAdvertiserReply) Reset() {
	*x = GetAdvertiserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdvertiserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertiserReply) ProtoMessage() {}

func (x *GetAdvertiserReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertiserReply.ProtoReflect.Descriptor instead.
func (*GetAdvertiserReply) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{7}
}

type ListAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAdvertiserRequest) Reset() {
	*x = ListAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdvertiserRequest) ProtoMessage() {}

func (x *ListAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*ListAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{8}
}

type ListAdvertiserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAdvertiserReply) Reset() {
	*x = ListAdvertiserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdvertiserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdvertiserReply) ProtoMessage() {}

func (x *ListAdvertiserReply) ProtoReflect() protoreflect.Message {
	mi := &file_common_advertiser_v1_advertiser_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdvertiserReply.ProtoReflect.Descriptor instead.
func (*ListAdvertiserReply) Descriptor() ([]byte, []int) {
	return file_common_advertiser_v1_advertiser_proto_rawDescGZIP(), []int{9}
}

var File_common_advertiser_v1_advertiser_proto protoreflect.FileDescriptor

var file_common_advertiser_v1_advertiser_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xd5, 0x04, 0x0a, 0x0a,
	0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x12, 0x76, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x12, 0x31,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x76, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x12, 0x31, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x76, 0x0a, 0x10, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x12, 0x31,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x61,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x6d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x72, 0x12, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x70, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x72, 0x12, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x42, 0x46, 0x0a, 0x18, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x50,
	0x01, 0x5a, 0x28, 0x61, 0x64, 0x2d, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x61, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_common_advertiser_v1_advertiser_proto_rawDescOnce sync.Once
	file_common_advertiser_v1_advertiser_proto_rawDescData = file_common_advertiser_v1_advertiser_proto_rawDesc
)

func file_common_advertiser_v1_advertiser_proto_rawDescGZIP() []byte {
	file_common_advertiser_v1_advertiser_proto_rawDescOnce.Do(func() {
		file_common_advertiser_v1_advertiser_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_advertiser_v1_advertiser_proto_rawDescData)
	})
	return file_common_advertiser_v1_advertiser_proto_rawDescData
}

var file_common_advertiser_v1_advertiser_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_common_advertiser_v1_advertiser_proto_goTypes = []any{
	(*CreateAdvertiserRequest)(nil), // 0: api.common.advertiser.v1.CreateAdvertiserRequest
	(*CreateAdvertiserReply)(nil),   // 1: api.common.advertiser.v1.CreateAdvertiserReply
	(*UpdateAdvertiserRequest)(nil), // 2: api.common.advertiser.v1.UpdateAdvertiserRequest
	(*UpdateAdvertiserReply)(nil),   // 3: api.common.advertiser.v1.UpdateAdvertiserReply
	(*DeleteAdvertiserRequest)(nil), // 4: api.common.advertiser.v1.DeleteAdvertiserRequest
	(*DeleteAdvertiserReply)(nil),   // 5: api.common.advertiser.v1.DeleteAdvertiserReply
	(*GetAdvertiserRequest)(nil),    // 6: api.common.advertiser.v1.GetAdvertiserRequest
	(*GetAdvertiserReply)(nil),      // 7: api.common.advertiser.v1.GetAdvertiserReply
	(*ListAdvertiserRequest)(nil),   // 8: api.common.advertiser.v1.ListAdvertiserRequest
	(*ListAdvertiserReply)(nil),     // 9: api.common.advertiser.v1.ListAdvertiserReply
}
var file_common_advertiser_v1_advertiser_proto_depIdxs = []int32{
	0, // 0: api.common.advertiser.v1.Advertiser.CreateAdvertiser:input_type -> api.common.advertiser.v1.CreateAdvertiserRequest
	2, // 1: api.common.advertiser.v1.Advertiser.UpdateAdvertiser:input_type -> api.common.advertiser.v1.UpdateAdvertiserRequest
	4, // 2: api.common.advertiser.v1.Advertiser.DeleteAdvertiser:input_type -> api.common.advertiser.v1.DeleteAdvertiserRequest
	6, // 3: api.common.advertiser.v1.Advertiser.GetAdvertiser:input_type -> api.common.advertiser.v1.GetAdvertiserRequest
	8, // 4: api.common.advertiser.v1.Advertiser.ListAdvertiser:input_type -> api.common.advertiser.v1.ListAdvertiserRequest
	1, // 5: api.common.advertiser.v1.Advertiser.CreateAdvertiser:output_type -> api.common.advertiser.v1.CreateAdvertiserReply
	3, // 6: api.common.advertiser.v1.Advertiser.UpdateAdvertiser:output_type -> api.common.advertiser.v1.UpdateAdvertiserReply
	5, // 7: api.common.advertiser.v1.Advertiser.DeleteAdvertiser:output_type -> api.common.advertiser.v1.DeleteAdvertiserReply
	7, // 8: api.common.advertiser.v1.Advertiser.GetAdvertiser:output_type -> api.common.advertiser.v1.GetAdvertiserReply
	9, // 9: api.common.advertiser.v1.Advertiser.ListAdvertiser:output_type -> api.common.advertiser.v1.ListAdvertiserReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_advertiser_v1_advertiser_proto_init() }
func file_common_advertiser_v1_advertiser_proto_init() {
	if File_common_advertiser_v1_advertiser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_advertiser_v1_advertiser_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateAdvertiserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateAdvertiserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteAdvertiserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetAdvertiserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_advertiser_v1_advertiser_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ListAdvertiserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_advertiser_v1_advertiser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_advertiser_v1_advertiser_proto_goTypes,
		DependencyIndexes: file_common_advertiser_v1_advertiser_proto_depIdxs,
		MessageInfos:      file_common_advertiser_v1_advertiser_proto_msgTypes,
	}.Build()
	File_common_advertiser_v1_advertiser_proto = out.File
	file_common_advertiser_v1_advertiser_proto_rawDesc = nil
	file_common_advertiser_v1_advertiser_proto_goTypes = nil
	file_common_advertiser_v1_advertiser_proto_depIdxs = nil
}
